# Generated by Django 5.2.5 on 2025-09-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0004_remove_food_bonus_section_alter_food_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('work_time_start', models.TimeField()),
                ('work_time_end', models.TimeField()),
                ('deliver_fee', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(related_name='menus', to='food.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'api_menu',
            },
        ),
    ]
