# Generated by Django 5.2.5 on 2025-09-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_restaurant_restaurant_manu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='manu',
            new_name='menu',
        ),
    ]
