# Generated by Django 5.2.5 on 2025-09-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_image_url'),
        ('restaurant', '0003_rename_manu_restaurant_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='food.category'),
            preserve_default=False,
        ),
    ]
