# Generated by Django 5.2.5 on 2025-09-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_categories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('bonus_price', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
                ('bonus_section', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'api_foods',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food.food')),
            ],
            options={
                'db_table': 'api_images',
            },
        ),
    ]
