# Generated by Django 5.2.5 on 2025-09-02 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='food.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='bonus_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
