# Generated by Django 5.2.5 on 2025-09-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_category_alter_food_bonus_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
