# Generated by Django 5.2.5 on 2025-09-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_image_url_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='bonus_section',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='food.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BonusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_count', models.PositiveIntegerField(default=0)),
                ('add', models.PositiveIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='food.food')),
            ],
            options={
                'db_table': 'api_bonus',
            },
        ),
    ]
