# Generated by Django 5.2.5 on 2025-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_food_bonus_section_alter_food_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
