# Generated by Django 5.2.5 on 2025-09-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_image_url'),
        ('restaurant', '0005_remove_menu_category_remove_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.category'),
        ),
    ]
